services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nautico2@
      MYSQL_DATABASE: hortifrutnectar
      MYSQL_USER: admin
      MYSQL_PASSWORD: nautico2@
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_app
    restart: always
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: nautico2@
      DB_NAME: hortifrutnectar
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:80"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  dbdata:
